import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import factory from '../ethereum/factory';
import { useState, useEffect, DOMElement } from 'react';
import { Card, Button } from 'semantic-ui-react';
import 'semantic-ui-css/semantic.min.css';
import { Layout } from '../components/MainComponents/Layout';

type Campaigns = {
	header: string;
	fluid: boolean;
	description: React.ReactNode;
};

const Home: NextPage = () => {
	const [campaigns, setCampaigns] = useState<string[]>([]);
	const [items, setItems] = useState<Campaigns[]>([]);

	useEffect(() => {
		(async () => {
			const campaingns = await factory.methods.getDeployedCampaigns().call();
			setCampaigns(campaingns);
		})();

		if (campaigns.length) {
			const items = campaigns.map((address) => {
				return {
					header: address,
					fluid: true,
					description: <a href='#'>View campaing</a>,
				};
			});
			setItems(items);
		}
	}, [campaigns]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Mulipage web3 app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<main className={styles.main}>
					<div>
						<Button
							floated='right'
							content='Create a compain'
							icon='add circle'
							labelPosition='right'
							primary
						/>
						<Card.Group items={items}></Card.Group>
					</div>
				</main>
			</Layout>
		</div>
	);
};

export default Home;
